/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.facebook.animated.gif;

public final class R {
    public static final class attr {
        public static final int actualImageResource = 0x7f010248;
        public static final int actualImageScaleType = 0x7f0101a8;
        public static final int actualImageUri = 0x7f010247;
        public static final int backgroundImage = 0x7f0101a9;
        public static final int fadeDuration = 0x7f01019d;
        public static final int failureImage = 0x7f0101a3;
        public static final int failureImageScaleType = 0x7f0101a4;
        public static final int overlayImage = 0x7f0101aa;
        public static final int placeholderImage = 0x7f01019f;
        public static final int placeholderImageScaleType = 0x7f0101a0;
        public static final int pressedStateOverlayImage = 0x7f0101ab;
        public static final int progressBarAutoRotateInterval = 0x7f0101a7;
        public static final int progressBarImage = 0x7f0101a5;
        public static final int progressBarImageScaleType = 0x7f0101a6;
        public static final int retryImage = 0x7f0101a1;
        public static final int retryImageScaleType = 0x7f0101a2;
        public static final int roundAsCircle = 0x7f0101ac;
        public static final int roundBottomLeft = 0x7f0101b1;
        public static final int roundBottomRight = 0x7f0101b0;
        public static final int roundTopLeft = 0x7f0101ae;
        public static final int roundTopRight = 0x7f0101af;
        public static final int roundWithOverlayColor = 0x7f0101b2;
        public static final int roundedCornerRadius = 0x7f0101ad;
        public static final int roundingBorderColor = 0x7f0101b4;
        public static final int roundingBorderPadding = 0x7f0101b5;
        public static final int roundingBorderWidth = 0x7f0101b3;
        public static final int viewAspectRatio = 0x7f01019e;
    }
    public static final class id {
        public static final int center = 0x7f100089;
        public static final int centerCrop = 0x7f100097;
        public static final int centerInside = 0x7f100098;
        public static final int fitBottomStart = 0x7f100099;
        public static final int fitCenter = 0x7f10009a;
        public static final int fitEnd = 0x7f10009b;
        public static final int fitStart = 0x7f10009c;
        public static final int fitXY = 0x7f10009d;
        public static final int focusCrop = 0x7f10009e;
        public static final int none = 0x7f100060;
    }
    public static final class styleable {
        public static final int[] GenericDraweeHierarchy = { 0x7f01019d, 0x7f01019e, 0x7f01019f, 0x7f0101a0, 0x7f0101a1, 0x7f0101a2, 0x7f0101a3, 0x7f0101a4, 0x7f0101a5, 0x7f0101a6, 0x7f0101a7, 0x7f0101a8, 0x7f0101a9, 0x7f0101aa, 0x7f0101ab, 0x7f0101ac, 0x7f0101ad, 0x7f0101ae, 0x7f0101af, 0x7f0101b0, 0x7f0101b1, 0x7f0101b2, 0x7f0101b3, 0x7f0101b4, 0x7f0101b5 };
        public static final int GenericDraweeHierarchy_fadeDuration = 0;
        public static final int GenericDraweeHierarchy_viewAspectRatio = 1;
        public static final int GenericDraweeHierarchy_placeholderImage = 2;
        public static final int GenericDraweeHierarchy_placeholderImageScaleType = 3;
        public static final int GenericDraweeHierarchy_retryImage = 4;
        public static final int GenericDraweeHierarchy_retryImageScaleType = 5;
        public static final int GenericDraweeHierarchy_failureImage = 6;
        public static final int GenericDraweeHierarchy_failureImageScaleType = 7;
        public static final int GenericDraweeHierarchy_progressBarImage = 8;
        public static final int GenericDraweeHierarchy_progressBarImageScaleType = 9;
        public static final int GenericDraweeHierarchy_progressBarAutoRotateInterval = 10;
        public static final int GenericDraweeHierarchy_actualImageScaleType = 11;
        public static final int GenericDraweeHierarchy_backgroundImage = 12;
        public static final int GenericDraweeHierarchy_overlayImage = 13;
        public static final int GenericDraweeHierarchy_pressedStateOverlayImage = 14;
        public static final int GenericDraweeHierarchy_roundAsCircle = 15;
        public static final int GenericDraweeHierarchy_roundedCornerRadius = 16;
        public static final int GenericDraweeHierarchy_roundTopLeft = 17;
        public static final int GenericDraweeHierarchy_roundTopRight = 18;
        public static final int GenericDraweeHierarchy_roundBottomRight = 19;
        public static final int GenericDraweeHierarchy_roundBottomLeft = 20;
        public static final int GenericDraweeHierarchy_roundWithOverlayColor = 21;
        public static final int GenericDraweeHierarchy_roundingBorderWidth = 22;
        public static final int GenericDraweeHierarchy_roundingBorderColor = 23;
        public static final int GenericDraweeHierarchy_roundingBorderPadding = 24;
        public static final int[] SimpleDraweeView = { 0x7f01019d, 0x7f01019e, 0x7f01019f, 0x7f0101a0, 0x7f0101a1, 0x7f0101a2, 0x7f0101a3, 0x7f0101a4, 0x7f0101a5, 0x7f0101a6, 0x7f0101a7, 0x7f0101a8, 0x7f0101a9, 0x7