/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.viewpagerindicator;

public final class R {
    public static final class attr {
        public static final int centered = 0x7f010005;
        public static final int clipPadding = 0x7f0102a3;
        public static final int fadeDelay = 0x7f0102bf;
        public static final int fadeLength = 0x7f0102c0;
        public static final int fades = 0x7f0102be;
        public static final int fillColor = 0x7f01013d;
        public static final int footerColor = 0x7f0102a4;
        public static final int footerIndicatorHeight = 0x7f0102a7;
        public static final int footerIndicatorStyle = 0x7f0102a6;
        public static final int footerIndicatorUnderlinePadding = 0x7f0102a8;
        public static final int footerLineHeight = 0x7f0102a5;
        public static final int footerPadding = 0x7f0102a9;
        public static final int gapWidth = 0x7f0101c1;
        public static final int linePosition = 0x7f0102aa;
        public static final int lineWidth = 0x7f0101c0;
        public static final int pageColor = 0x7f01013e;
        public static final int radius = 0x7f01013f;
        public static final int selectedBold = 0x7f0102ab;
        public static final int selectedColor = 0x7f010048;
        public static final int snap = 0x7f010140;
        public static final int strokeColor = 0x7f010141;
        public static final int strokeWidth = 0x7f010057;
        public static final int titlePadding = 0x7f0102ac;
        public static final int topPadding = 0x7f0102ad;
        public static final int unselectedColor = 0x7f01005a;
        public static final int vpiCirclePageIndicatorStyle = 0x7f0102c6;
        public static final int vpiIconPageIndicatorStyle = 0x7f0102c7;
        public static final int vpiLinePageIndicatorStyle = 0x7f0102c8;
        public static final int vpiTabPageIndicatorStyle = 0x7f0102ca;
        public static final int vpiTitlePageIndicatorStyle = 0x7f0102c9;
        public static final int vpiUnderlinePageIndicatorStyle = 0x7f0102cb;
    }
    public static final c